name       : haskell-sop-core
version    : 0.5.0.0
release    : 1
source     :
    - https://hackage.haskell.org/package/sop-core-0.5.0.0/sop-core-0.5.0.0.tar.gz : ff8f3d787a444a4628fb3111c444608b1a901d80f759108ec96e68f2406ef88b
license    : BSD-3-Clause
component  : programming.haskell
summary    : Implementation of n-ary sums and n-ary products.
description: |
    Implementation of n-ary sums and n-ary products.
builddeps  :
    - ghc-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - ghc-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
